FROM python

RUN mkdir -p /opt/tradingview2exch

COPY . /opt/tradingview2exch/

WORKDIR /opt/tradingview2exch

RUN pip3 install -r requirements.txt

RUN chmod +x entrypoint.sh

RUN rm db.sqlite3 || true
RUN mkdir db

EXPOSE 8000

ENTRYPOINT ./entrypoint.sh