# Generated by Django 5.2.7 on 2026-03-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook_Receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
