# Generated by Django 6.0.7 on 2026-08-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add execution_status so a rejected order can be retried (T-001)."""

    dependencies = [
        ('Webhook_Receiver', '0003_rename_webhook_to_pascalcase_and_snake_case_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='execution_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Received, exchange not yet called'),
                    ('EXECUTED', 'Accepted by the exchange'),
                    ('REJECTED', 'Refused by the exchange; safe to retry'),
                    ('UNKNOWN', 'Call failed without proving non-execution'),
                ],
                db_index=True,
                default='PENDING',
                max_length=10,
            ),
        ),
    ]
