from django.db import models

""" Defines the Alerta model representing an alert generated by the system. """


class webhook(models.Model):
    """ 
    Field to store the symbol associated with the alert. 
    """
    symbol = models.CharField(max_length=30)

    """ 
    Field to store the exchange associated with the alert. 
    """
    exchange = models.CharField(max_length=30)

    """ 
    Field to store the time the alert was generated. Set as the primary key. 
    """
    time = models.DateTimeField(primary_key=True)

    """ 
    Field to store the time interval associated with the alert. 
    """
    interval = models.DecimalField(max_digits=5, decimal_places=2)

    """ 
    Field to store the size associated with the alert. 
    """
    size = models.DecimalField(max_digits=12, decimal_places=6)

    """ 
    Field to store the side associated with the alert (e.g., buy or sell). 
    """
    side = models.CharField(max_length=30)

    """ 
    Field to store the price in USDT of the alert. 
    """
    price = models.DecimalField(max_digits=12, decimal_places=6)

    """ 
    Field to store the order ID associated with the alert. 
    """
    orderId = models.CharField(max_length=30)

    """ 
    Field to store the market position. 
    """
    marketPosition = models.DecimalField(max_digits=12, decimal_places=6)

    """ 
    Field to store the previous market position. 
    """
    marketPrevPosition = models.DecimalField(max_digits=12, decimal_places=6)

    """ 
    Field to store the type of alert. 
    """
    type = models.CharField(max_length=30)

    """ 
    Method that returns a readable representation of the alert. 
    """

    def __str__(self):
        return (f"{self.symbol} - {self.exchange} - {self.time} - {self.interval} - {self.size} - "
                f"{self.side} - {self.price} - {self.orderId} - {self.marketPosition} - "
                f"{self.marketPrevPosition} - {self.type}")
