# Generated by Django 5.0.7 on 2024-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='binanceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('size', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
